root_name: Root
lobby_name: Lobby
volunteer_name: Medic volunteers
chill_name: Chill room
pug_format_name: Pug {}
BLU: BLU
RED: RED
max_pugs: 5
password_length: 12
rcon_length: 20
tf2_port: 27015
min_total_players: 6
region_priorities:
- us-east-2
- us-east-1
- us-west-2
- us-west-1
instance_priorities:
- c5.large
- t3.small
- t3a.small
- c5a.large
aws_key_id_filename: secrets/aws_key_id
aws_access_key_filename: secrets/aws_access_key
ec2_ami: ami-03ea1b5724483c472
ec2_secgroupids:
- sg-0508f87e0dba26c1a
tf2_config_path: /home/ubuntu/tf2server/hlserver/tf/cfg/server.cfg
bot_data_store_name: mumble_bot_store.dat
use_mumble_monitoring: true
medic_immunity_reset_hours: 6
autoroll_delay: 10
end_pug_delay: 20
ec2_retry_delay: 10
ec2_num_retries: 10